import "../styles/global.scss";
import { Roboto, Poppins } from "next/font/google";
import Provider from "./context/Provider";
import Header from "./components/Header";
import Footer from "./components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Provider>
      <html
        lang="en"
        className={`${roboto.variable} ${poppins.variable} font-primary flex just-cont`}
      >
        <body className="min-h-[100vh] w-[96rem] grid grid-rows-[auto 1fr auto] bg-offWhite">
          <Header />
          <main className="overflow-hidden">{children}</main>
          <Footer />
        </body>
      </html>
    </Provider>
  );
};

export default Layout;
